version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
hooks:
  AfterInstall:
    - location: install_nginx.sh
      timeout: 300
      runas: root
  ApllicationStart:
    - location: start_nginx.sh
      timeout: 300
      runas: r
